### ISSUE TITLE
Throw an Exception when client tries to interact with a non-compatible server version

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-client#210]
As @tcompa and I experienced today, having separate client & server versions can lead to incompatibilities and hard-to-trace errors. Would be good if the client could throw a warning or an exception if it interacts with an incompatible server version.
Not relevant for the web client, but the CLI client could be e.g. version 0.1.0 and try to interact with our 0.3.0 server down the road.

Also, such a warning is an easy flag to raise when installation issues come up.

How we define what server version works with which client version may be a trickier debate to be had and we shouldn't be unnecessarily strict here.

**Comment by tcompa** [comment]
Possible option:
* On the client side, define a range of allowed server and API versions (not that in principle we could bind the major server version with the API version).
* Include a [FastAPI middleware](https://fastapi.tiangolo.com/tutorial/middleware/) to all routers, that exposes the server and API versions.
* If the server or API version is not in the allowed range, fail gracefully.

**Comment by tcompa** [comment]
At least a warning, for different minor.

**Comment by tcompa** [comment]
Side note: since we have now removed the server/client-shared fractal-common submodule, the discussion about server/client compatibility can resume. This is not meant to be a high-priority discussion.

The starting point could be to encode a **minimum required fractal-server version** in each fractal-client release.
Then, for each client command, we would:
* fetch the fractal-server version: this would be an additional API call, at first, but then we can cache this information as usual (with the appropriate mechanism for cache invalidation)
* check that the version is above the minimum required version and proceed, or raise an informative error

This works this way:
* fractal-server 3.8 implements a new endpoint or updates an existing one
* fractal-client 9.4 uses this new endpoint
* --> fractal-client 9.4 should fail (gracefully) when it communicates with a fractal-server-3.7 instance

Note that this only fixes half of the problem, cause the following scenario is still bugged:
* fractal-server 3.8 implements a new endpoint or updates an existing one
* fractal-client 8.2 (an old version) is based on the old endpoint from fractal-sever 3.7
* --> how can fractal-client 8.2 know that the maximum supported version is 3.7? this is unclear to me

Side comment: after we design this mechanism, we should also add a matrix-based test to check multiple fractal-server versions

**Comment by tcompa** [comment]
Something more about this old issue. This is not meant to be _the_ solution, but something to explore.

1. We have now skipped v1.4.1 of CLI client, to remain aligned with fractal-server (note that it would also be OK/better to produce a dummy v1.4.1 which is identical to v1.4.0, although it's hard to do it retroactively).
2. For this scenario (fractal-server needs an update, even if fractal-client does not), we will always try to follow this rule (that is, create a dummy fractal-client release).
3. TBD what to do in the other case, that is, when fractal-client needs an update but fractal-server does not. Note that this is less frequent, but it could happen.
4. The version match is not a hard requirement for now, but it could be the way we address this issue in the future, by strictly requiring the same major.minor.patch version (while being flexible for pre-releases).

**Comment by jluethi** [comment]
=> let's go with a simple doc page for the moment

**Comment by tcompa** [comment]
Closed for now, by adding https://fractal-analytics-platform.github.io/fractal-client/versions/.
We'll revisit the issue in the future, especially if there start to be more active Fractal instances handled by different people.
